### ISSUE TITLE
Allow playing of restricted videos

### ISSUE THREAD

**Issue by CDaut** [Nirusu99/nirubot#4]
Currently you cannot play age restricted videos. Example: https://youtu.be/x6RVFT4TNWE

**Comment by narrrl** [comment]
Oh no not again

**Comment by CDaut** [comment]
Yes of course!
Please also take a look at this other example: https://youtu.be/dQw4w9WgXcQ

**Comment by narrrl** [comment]
fixed with this [commit](https://github.com/Nirusu99/nirubot/commit/b0afb2d266371fd8cfefa164547009e91b9a47bb)
